### ISSUE TITLE
suggestion: add surge as deployment tool.

### ISSUE THREAD

**Issue by sintaxi** [drKraken/setup.sh#3]
This is great setup. 

If your looking for a good deployment solution that doesn't require any prior setup I would look at http://surge.sh.

#### install... 

    npm install sugre -g`

#### surge takes two args project path and domain...

    surge ./path/to/www example.com

or you just run `surge` from the project root and you will be prompted for the necessary args. 

[read more about it here](https://medium.com/surge-sh/introducing-surge-the-cdn-for-front-end-developers-b4a50a61bcfc). Let me know if you have any questions.

**Comment by drKraken** [comment]
Incredibly useful tool. Thanks for advice. Will add it,certainly.
